### ISSUE TITLE
Spring vault docs shows hyperlink instead of text 

### ISSUE THREAD

**Issue by avinash28196** [spring-guides/gs-vault-config#12]
I was going through the spring vault docs [Link to the docs](https://spring.io/guides/gs/vault-config/) and saw an issue with adoc file. Instead of including the content mentioned in the URI, it shows the URI itself. 

Upon looking[ Adoc guideline ](https://docs.asciidoctor.org/asciidoc/latest/directives/include-uri/)It says 
```
The include directive recognizes when the target is a URI and can include the content referenced by that URI.
This example demonstrates how to include an AsciiDoc file from a GitHub repository directly into your document.
include::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc[]
For security reasons, this capability is not enabled by default. To allow content to be read from a URI, 
you must enable the URI read permission by:
```
**Screenshot for reference:**
![image](https://user-images.githubusercontent.com/16860886/119803824-6ecf1300-befd-11eb-9242-0ce1810c9a76.png)

**Comment by robertmcnees** [comment]
Hi @avinash28196. Thanks for the issue. As you've found in the provided link, this is a common scenario with asciidoc and not rendering the include directives is a security choice.

I'm not sure if the screenshot provided is from GitHub or your IDE. If it is from your IDE, you should be able to modify the security settings so that it renders the include directives locally. In GitHub, it is not so straightforward. I created [this issue](https://github.com/spring-guides/getting-started-guides/issues/162) in our template repository to track this at a higher level. All of our guides, and indeed any asciidoc on GitHub, has the same issue.

The deploy script we use should render these includes, so you should not see this in the [rendered guide](https://spring.io/guides/gs/vault-config).

I'll close this issue in favor of tracking it on the template repository instead. More context, history, and potential solutions can be found there.
